### ISSUE TITLE
TV turns itself on in the early hours of the morning

### ISSUE THREAD

**Issue by sOckhamSter** [sOckhamSter/lgtv-bridge#1]
I *think* that this is caused by the TV checking to see if there are any updates available. It probably starts responding to pings on the network, so the lgtv-bridge thinks that the TV has been turned on, sends a request out to the WebCoRE piston, which turns on the virtual switch, which fires the piston again and sends out the magic packet that turns the TV on... I think. Need to experiment to get to the root cause. Two possible fixes that I'm considering:
1) Somehow stop the piston from sending out the virtual switch is programatically changed.
2) Set an ignore timeframe in lgtv-bridge or the piston that ignores any requests to power on/off the TV during a certain time period.

**Comment by sOckhamSter** [comment]
I've updated the WebCoRE piston, see import code xcsaq. The piston now sets a global variable if it has been executed externally with the TurnIt parameter. It then exits as soon as it has toggled the switch, which activates the piston again through the switch on/off events. The piston then checks to see if the global variable has been set and if so, it does not send a power on/off request to the bridge. It also resets the global variable so as it isn't bypassed next time, and as a fallback it also resets the variable if the switch hasn't changed status in 20 seconds (so it's stable and on or off).

I'll leave the issue open for a few days while the fix is tested.

**Comment by santidog** [comment]
Thanks for this repo, was exactly what I looking for.  Can you update the readme to add the global variable creation in webcore, I realized that it missing was causing a NPE on the piston and things are now working perfectly for me so far.  Thanks again!

**Comment by sOckhamSter** [comment]
Added as step 6! Thanks for spotting that bit of missing information.
